#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("knight_mares_project.Resource", IsApplication=true)]

namespace knight_mares_project
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int backgroundFireflydarker = 2130837505;
			
			// aapt resource value: 0x7F020000
			public const int back_arrow = 2130837504;
			
			// aapt resource value: 0x7F020002
			public const int cutearmsupghostsmol = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cutearmsupghostsmolblue = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int cutearmsupghostsmolpurp = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int forest = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ghostpattern2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int jackolanternremoved2 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int knightpic = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int little_red_flag = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int snowtreesmol = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnReturn = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnStart = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnSubmit = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int difficulty = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int displayDifficulty = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int flBoard = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int sbDifficulty = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int tvDisplayDifficulty = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int tvTime = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int tvTitle = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int tvWinMessage = 2130903050;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int board_view = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int difficulty_dialog = 2130968578;
			
			// aapt resource value: 0x7F060005
			public const int abc_action_bar_elevation_material = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int abc_action_bar_icon_vertical_padding_material = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int abc_action_bar_overflow_padding_end_material = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int abc_action_bar_overflow_padding_start_material = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int abc_action_bar_stacked_max_height = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int abc_action_bar_stacked_tab_max_width = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int abc_action_bar_subtitle_bottom_margin_material = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int abc_action_bar_subtitle_top_margin_material = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int abc_action_button_min_height_material = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int abc_action_button_min_width_material = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int abc_action_button_min_width_overflow_material = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int abc_alert_dialog_button_bar_height = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int abc_alert_dialog_button_dimen = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int abc_button_inset_horizontal_material = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int abc_button_inset_vertical_material = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int abc_button_padding_horizontal_material = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int abc_button_padding_vertical_material = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int abc_cascading_menus_min_smallest_width = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int abc_config_prefDialogWidth = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int abc_control_corner_material = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int abc_control_inset_material = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int abc_control_padding_material = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int abc_dialog_corner_radius_material = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int abc_dialog_fixed_height_major = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int abc_dialog_fixed_height_minor = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int abc_dialog_fixed_width_major = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int abc_dialog_fixed_width_minor = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int abc_dialog_list_padding_bottom_no_buttons = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int abc_dialog_list_padding_top_no_title = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int abc_dialog_min_width_major = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int abc_dialog_min_width_minor = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int abc_dialog_padding_material = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int abc_dialog_padding_top_material = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int abc_dialog_title_divider_material = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int abc_disabled_alpha_material_dark = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int abc_disabled_alpha_material_light = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int abc_dropdownitem_icon_width = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int abc_dropdownitem_text_padding_left = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int abc_dropdownitem_text_padding_right = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int abc_edit_text_inset_bottom_material = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int abc_edit_text_inset_horizontal_material = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int abc_edit_text_inset_top_material = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int abc_floating_window_z = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int abc_list_item_height_large_material = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int abc_list_item_height_material = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int abc_list_item_height_small_material = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int abc_list_item_padding_horizontal_material = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int abc_panel_menu_list_width = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int abc_progress_bar_height_material = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int abc_search_view_preferred_height = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int abc_search_view_preferred_width = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int abc_seekbar_track_background_height_material = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int abc_seekbar_track_progress_height_material = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int abc_select_dialog_padding_start_material = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int abc_switch_padding = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int abc_text_size_body_1_material = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int abc_text_size_body_2_material = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int abc_text_size_button_material = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int abc_text_size_caption_material = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int abc_text_size_display_1_material = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int abc_text_size_display_2_material = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int abc_text_size_display_3_material = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int abc_text_size_display_4_material = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int abc_text_size_headline_material = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int abc_text_size_large_material = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int abc_text_size_medium_material = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int abc_text_size_menu_header_material = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int abc_text_size_menu_material = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int abc_text_size_small_material = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int abc_text_size_subhead_material = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int abc_text_size_subtitle_material_toolbar = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int abc_text_size_title_material = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int abc_text_size_title_material_toolbar = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int browser_actions_context_menu_max_width = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int browser_actions_context_menu_min_padding = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int cardview_compat_inset_shadow = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int cardview_default_elevation = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int cardview_default_radius = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int compat_button_inset_horizontal_material = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int compat_button_inset_vertical_material = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int compat_button_padding_horizontal_material = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int compat_button_padding_vertical_material = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int compat_control_corner_material = 2131099735;
			
			// aapt resource value: 0x7F060058
			public const int compat_notification_large_icon_max_height = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int compat_notification_large_icon_max_width = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int def_drawer_elevation = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int design_appbar_elevation = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int design_bottom_navigation_active_item_max_width = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int design_bottom_navigation_active_item_min_width = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int design_bottom_navigation_active_text_size = 2131099742;
			
			// aapt resource value: 0x7F06005F
			public const int design_bottom_navigation_elevation = 2131099743;
			
			// aapt resource value: 0x7F060060
			public const int design_bottom_navigation_height = 2131099744;
			
			// aapt resource value: 0x7F060061
			public const int design_bottom_navigation_icon_size = 2131099745;
			
			// aapt resource value: 0x7F060062
			public const int design_bottom_navigation_item_max_width = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int design_bottom_navigation_item_min_width = 2131099747;
			
			// aapt resource value: 0x7F060064
			public const int design_bottom_navigation_margin = 2131099748;
			
			// aapt resource value: 0x7F060065
			public const int design_bottom_navigation_shadow_height = 2131099749;
			
			// aapt resource value: 0x7F060066
			public const int design_bottom_navigation_text_size = 2131099750;
			
			// aapt resource value: 0x7F060067
			public const int design_bottom_sheet_modal_elevation = 2131099751;
			
			// aapt resource value: 0x7F060068
			public const int design_bottom_sheet_peek_height_min = 2131099752;
			
			// aapt resource value: 0x7F060069
			public const int design_fab_border_width = 2131099753;
			
			// aapt resource value: 0x7F06006A
			public const int design_fab_elevation = 2131099754;
			
			// aapt resource value: 0x7F06006B
			public const int design_fab_image_size = 2131099755;
			
			// aapt resource value: 0x7F06006C
			public const int design_fab_size_mini = 2131099756;
			
			// aapt resource value: 0x7F06006D
			public const int design_fab_size_normal = 2131099757;
			
			// aapt resource value: 0x7F06006E
			public const int design_fab_translation_z_hovered_focused = 2131099758;
			
			// aapt resource value: 0x7F06006F
			public const int design_fab_translation_z_pressed = 2131099759;
			
			// aapt resource value: 0x7F060070
			public const int design_navigation_elevation = 2131099760;
			
			// aapt resource value: 0x7F060071
			public const int design_navigation_icon_padding = 2131099761;
			
			// aapt resource value: 0x7F060072
			public const int design_navigation_icon_size = 2131099762;
			
			// aapt resource value: 0x7F060073
			public const int design_navigation_item_horizontal_padding = 2131099763;
			
			// aapt resource value: 0x7F060074
			public const int design_navigation_item_icon_padding = 2131099764;
			
			// aapt resource value: 0x7F060075
			public const int design_navigation_max_width = 2131099765;
			
			// aapt resource value: 0x7F060076
			public const int design_navigation_padding_bottom = 2131099766;
			
			// aapt resource value: 0x7F060077
			public const int design_navigation_separator_vertical_padding = 2131099767;
			
			// aapt resource value: 0x7F060078
			public const int design_snackbar_action_inline_max_width = 2131099768;
			
			// aapt resource value: 0x7F060079
			public const int design_snackbar_background_corner_radius = 2131099769;
			
			// aapt resource value: 0x7F06007A
			public const int design_snackbar_elevation = 2131099770;
			
			// aapt resource value: 0x7F06007B
			public const int design_snackbar_extra_spacing_horizontal = 2131099771;
			
			// aapt resource value: 0x7F06007C
			public const int design_snackbar_max_width = 2131099772;
			
			// aapt resource value: 0x7F06007D
			public const int design_snackbar_min_width = 2131099773;
			
			// aapt resource value: 0x7F06007E
			public const int design_snackbar_padding_horizontal = 2131099774;
			
			// aapt resource value: 0x7F06007F
			public const int design_snackbar_padding_vertical = 2131099775;
			
			// aapt resource value: 0x7F060080
			public const int design_snackbar_padding_vertical_2lines = 2131099776;
			
			// aapt resource value: 0x7F060081
			public const int design_snackbar_text_size = 2131099777;
			
			// aapt resource value: 0x7F060082
			public const int design_tab_max_width = 2131099778;
			
			// aapt resource value: 0x7F060083
			public const int design_tab_scrollable_min_width = 2131099779;
			
			// aapt resource value: 0x7F060084
			public const int design_tab_text_size = 2131099780;
			
			// aapt resource value: 0x7F060085
			public const int design_tab_text_size_2line = 2131099781;
			
			// aapt resource value: 0x7F060086
			public const int design_textinput_caption_translate_y = 2131099782;
			
			// aapt resource value: 0x7F060087
			public const int disabled_alpha_material_dark = 2131099783;
			
			// aapt resource value: 0x7F060088
			public const int disabled_alpha_material_light = 2131099784;
			
			// aapt resource value: 0x7F060089
			public const int fastscroll_default_thickness = 2131099785;
			
			// aapt resource value: 0x7F06008A
			public const int fastscroll_margin = 2131099786;
			
			// aapt resource value: 0x7F06008B
			public const int fastscroll_minimum_range = 2131099787;
			
			// aapt resource value: 0x7F06008C
			public const int highlight_alpha_material_colored = 2131099788;
			
			// aapt resource value: 0x7F06008D
			public const int highlight_alpha_material_dark = 2131099789;
			
			// aapt resource value: 0x7F06008E
			public const int highlight_alpha_material_light = 2131099790;
			
			// aapt resource value: 0x7F06008F
			public const int hint_alpha_material_dark = 2131099791;
			
			// aapt resource value: 0x7F060090
			public const int hint_alpha_material_light = 2131099792;
			
			// aapt resource value: 0x7F060091
			public const int hint_pressed_alpha_material_dark = 2131099793;
			
			// aapt resource value: 0x7F060092
			public const int hint_pressed_alpha_material_light = 2131099794;
			
			// aapt resource value: 0x7F060093
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099795;
			
			// aapt resource value: 0x7F060094
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099796;
			
			// aapt resource value: 0x7F060095
			public const int item_touch_helper_swipe_escape_velocity = 2131099797;
			
			// aapt resource value: 0x7F060096
			public const int mtrl_bottomappbar_fabOffsetEndMode = 2131099798;
			
			// aapt resource value: 0x7F060097
			public const int mtrl_bottomappbar_fab_cradle_margin = 2131099799;
			
			// aapt resource value: 0x7F060098
			public const int mtrl_bottomappbar_fab_cradle_rounded_corner_radius = 2131099800;
			
			// aapt resource value: 0x7F060099
			public const int mtrl_bottomappbar_fab_cradle_vertical_offset = 2131099801;
			
			// aapt resource value: 0x7F06009A
			public const int mtrl_bottomappbar_height = 2131099802;
			
			// aapt resource value: 0x7F06009B
			public const int mtrl_btn_corner_radius = 2131099803;
			
			// aapt resource value: 0x7F06009C
			public const int mtrl_btn_dialog_btn_min_width = 2131099804;
			
			// aapt resource value: 0x7F06009D
			public const int mtrl_btn_disabled_elevation = 2131099805;
			
			// aapt resource value: 0x7F06009E
			public const int mtrl_btn_disabled_z = 2131099806;
			
			// aapt resource value: 0x7F06009F
			public const int mtrl_btn_elevation = 2131099807;
			
			// aapt resource value: 0x7F0600A0
			public const int mtrl_btn_focused_z = 2131099808;
			
			// aapt resource value: 0x7F0600A1
			public const int mtrl_btn_hovered_z = 2131099809;
			
			// aapt resource value: 0x7F0600A2
			public const int mtrl_btn_icon_btn_padding_left = 2131099810;
			
			// aapt resource value: 0x7F0600A3
			public const int mtrl_btn_icon_padding = 2131099811;
			
			// aapt resource value: 0x7F0600A4
			public const int mtrl_btn_inset = 2131099812;
			
			// aapt resource value: 0x7F0600A5
			public const int mtrl_btn_letter_spacing = 2131099813;
			
			// aapt resource value: 0x7F0600A6
			public const int mtrl_btn_padding_bottom = 2131099814;
			
			// aapt resource value: 0x7F0600A7
			public const int mtrl_btn_padding_left = 2131099815;
			
			// aapt resource value: 0x7F0600A8
			public const int mtrl_btn_padding_right = 2131099816;
			
			// aapt resource value: 0x7F0600A9
			public const int mtrl_btn_padding_top = 2131099817;
			
			// aapt resource value: 0x7F0600AA
			public const int mtrl_btn_pressed_z = 2131099818;
			
			// aapt resource value: 0x7F0600AB
			public const int mtrl_btn_stroke_size = 2131099819;
			
			// aapt resource value: 0x7F0600AC
			public const int mtrl_btn_text_btn_icon_padding = 2131099820;
			
			// aapt resource value: 0x7F0600AD
			public const int mtrl_btn_text_btn_padding_left = 2131099821;
			
			// aapt resource value: 0x7F0600AE
			public const int mtrl_btn_text_btn_padding_right = 2131099822;
			
			// aapt resource value: 0x7F0600AF
			public const int mtrl_btn_text_size = 2131099823;
			
			// aapt resource value: 0x7F0600B0
			public const int mtrl_btn_z = 2131099824;
			
			// aapt resource value: 0x7F0600B1
			public const int mtrl_card_elevation = 2131099825;
			
			// aapt resource value: 0x7F0600B2
			public const int mtrl_card_spacing = 2131099826;
			
			// aapt resource value: 0x7F0600B3
			public const int mtrl_chip_pressed_translation_z = 2131099827;
			
			// aapt resource value: 0x7F0600B4
			public const int mtrl_chip_text_size = 2131099828;
			
			// aapt resource value: 0x7F0600B5
			public const int mtrl_fab_elevation = 2131099829;
			
			// aapt resource value: 0x7F0600B6
			public const int mtrl_fab_translation_z_hovered_focused = 2131099830;
			
			// aapt resource value: 0x7F0600B7
			public const int mtrl_fab_translation_z_pressed = 2131099831;
			
			// aapt resource value: 0x7F0600B8
			public const int mtrl_navigation_elevation = 2131099832;
			
			// aapt resource value: 0x7F0600B9
			public const int mtrl_navigation_item_horizontal_padding = 2131099833;
			
			// aapt resource value: 0x7F0600BA
			public const int mtrl_navigation_item_icon_padding = 2131099834;
			
			// aapt resource value: 0x7F0600BB
			public const int mtrl_snackbar_background_corner_radius = 2131099835;
			
			// aapt resource value: 0x7F0600BC
			public const int mtrl_snackbar_margin = 2131099836;
			
			// aapt resource value: 0x7F0600BD
			public const int mtrl_textinput_box_bottom_offset = 2131099837;
			
			// aapt resource value: 0x7F0600BE
			public const int mtrl_textinput_box_corner_radius_medium = 2131099838;
			
			// aapt resource value: 0x7F0600BF
			public const int mtrl_textinput_box_corner_radius_small = 2131099839;
			
			// aapt resource value: 0x7F0600C0
			public const int mtrl_textinput_box_label_cutout_padding = 2131099840;
			
			// aapt resource value: 0x7F0600C1
			public const int mtrl_textinput_box_padding_end = 2131099841;
			
			// aapt resource value: 0x7F0600C2
			public const int mtrl_textinput_box_stroke_width_default = 2131099842;
			
			// aapt resource value: 0x7F0600C3
			public const int mtrl_textinput_box_stroke_width_focused = 2131099843;
			
			// aapt resource value: 0x7F0600C4
			public const int mtrl_textinput_outline_box_expanded_padding = 2131099844;
			
			// aapt resource value: 0x7F0600C5
			public const int mtrl_toolbar_default_height = 2131099845;
			
			// aapt resource value: 0x7F0600C6
			public const int notification_action_icon_size = 2131099846;
			
			// aapt resource value: 0x7F0600C7
			public const int notification_action_text_size = 2131099847;
			
			// aapt resource value: 0x7F0600C8
			public const int notification_big_circle_margin = 2131099848;
			
			// aapt resource value: 0x7F0600C9
			public const int notification_content_margin_start = 2131099849;
			
			// aapt resource value: 0x7F0600CA
			public const int notification_large_icon_height = 2131099850;
			
			// aapt resource value: 0x7F0600CB
			public const int notification_large_icon_width = 2131099851;
			
			// aapt resource value: 0x7F0600CC
			public const int notification_main_column_padding_top = 2131099852;
			
			// aapt resource value: 0x7F0600CD
			public const int notification_media_narrow_margin = 2131099853;
			
			// aapt resource value: 0x7F0600CE
			public const int notification_right_icon_size = 2131099854;
			
			// aapt resource value: 0x7F0600CF
			public const int notification_right_side_padding_top = 2131099855;
			
			// aapt resource value: 0x7F0600D0
			public const int notification_small_icon_background_padding = 2131099856;
			
			// aapt resource value: 0x7F0600D1
			public const int notification_small_icon_size_as_large = 2131099857;
			
			// aapt resource value: 0x7F0600D2
			public const int notification_subtext_size = 2131099858;
			
			// aapt resource value: 0x7F0600D3
			public const int notification_top_pad = 2131099859;
			
			// aapt resource value: 0x7F0600D4
			public const int notification_top_pad_large_text = 2131099860;
			
			// aapt resource value: 0x7F0600D5
			public const int tooltip_corner_radius = 2131099861;
			
			// aapt resource value: 0x7F0600D6
			public const int tooltip_horizontal_padding = 2131099862;
			
			// aapt resource value: 0x7F0600D7
			public const int tooltip_margin = 2131099863;
			
			// aapt resource value: 0x7F0600D8
			public const int tooltip_precise_anchor_extra_offset = 2131099864;
			
			// aapt resource value: 0x7F0600D9
			public const int tooltip_precise_anchor_threshold = 2131099865;
			
			// aapt resource value: 0x7F0600DA
			public const int tooltip_vertical_padding = 2131099866;
			
			// aapt resource value: 0x7F0600DB
			public const int tooltip_y_offset_non_touch = 2131099867;
			
			// aapt resource value: 0x7F0600DC
			public const int tooltip_y_offset_touch = 2131099868;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070006
			public const int abc_ab_share_pack_mtrl_alpha = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int abc_action_bar_item_background_material = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int abc_btn_borderless_material = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int abc_btn_check_material = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int abc_btn_check_material_anim = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int abc_btn_check_to_on_mtrl_000 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int abc_btn_check_to_on_mtrl_015 = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int abc_btn_colored_material = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int abc_btn_default_mtrl_shape = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int abc_btn_radio_material = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int abc_btn_radio_material_anim = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int abc_btn_radio_to_on_mtrl_000 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int abc_btn_radio_to_on_mtrl_015 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int abc_btn_switch_to_on_mtrl_00001 = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int abc_btn_switch_to_on_mtrl_00012 = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int abc_cab_background_internal_bg = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int abc_cab_background_top_material = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int abc_cab_background_top_mtrl_alpha = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int abc_control_background_material = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int abc_dialog_material_background = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int abc_edit_text_material = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int abc_ic_ab_back_material = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int abc_ic_arrow_drop_right_black_24dp = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int abc_ic_clear_material = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int abc_ic_commit_search_api_mtrl_alpha = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int abc_ic_go_search_api_material = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int abc_ic_menu_copy_mtrl_am_alpha = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int abc_ic_menu_cut_mtrl_alpha = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int abc_ic_menu_overflow_material = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int abc_ic_menu_paste_mtrl_am_alpha = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int abc_ic_menu_selectall_mtrl_alpha = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int abc_ic_menu_share_mtrl_alpha = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int abc_ic_search_api_material = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int abc_ic_star_black_16dp = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int abc_ic_star_black_36dp = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int abc_ic_star_black_48dp = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int abc_ic_star_half_black_16dp = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int abc_ic_star_half_black_36dp = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int abc_ic_star_half_black_48dp = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int abc_ic_voice_search_api_material = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int abc_item_background_holo_dark = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int abc_item_background_holo_light = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int abc_list_divider_material = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int abc_list_divider_mtrl_alpha = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int abc_list_focused_holo = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int abc_list_longpressed_holo = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int abc_list_pressed_holo_dark = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int abc_list_pressed_holo_light = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int abc_list_selector_background_transition_holo_dark = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int abc_list_selector_background_transition_holo_light = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int abc_list_selector_disabled_holo_dark = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int abc_list_selector_disabled_holo_light = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int abc_list_selector_holo_dark = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int abc_list_selector_holo_light = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int abc_menu_hardkey_panel_mtrl_mult = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int abc_popup_background_mtrl_mult = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int abc_ratingbar_indicator_material = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int abc_ratingbar_material = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int abc_ratingbar_small_material = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int abc_scrubber_control_off_mtrl_alpha = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int abc_scrubber_control_to_pressed_mtrl_000 = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int abc_scrubber_control_to_pressed_mtrl_005 = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int abc_scrubber_primary_mtrl_alpha = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int abc_scrubber_track_mtrl_alpha = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int abc_seekbar_thumb_material = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int abc_seekbar_tick_mark_material = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int abc_seekbar_track_material = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int abc_spinner_mtrl_am_alpha = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int abc_spinner_textfield_background_material = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int abc_switch_thumb_material = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int abc_switch_track_mtrl_alpha = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int abc_tab_indicator_material = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int abc_tab_indicator_mtrl_alpha = 2131165262;
			
			// aapt resource value: 0x7F070056
			public const int abc_textfield_activated_mtrl_alpha = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int abc_textfield_default_mtrl_alpha = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int abc_textfield_search_activated_mtrl_alpha = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int abc_textfield_search_default_mtrl_alpha = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int abc_textfield_search_material = 2131165274;
			
			// aapt resource value: 0x7F07004F
			public const int abc_text_cursor_material = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int abc_text_select_handle_left_mtrl_dark = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int abc_text_select_handle_left_mtrl_light = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int abc_text_select_handle_middle_mtrl_dark = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int abc_text_select_handle_middle_mtrl_light = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int abc_text_select_handle_right_mtrl_dark = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int abc_text_select_handle_right_mtrl_light = 2131165269;
			
			// aapt resource value: 0x7F07005B
			public const int abc_vector_test = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int avd_hide_password = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int avd_show_password = 2131165277;
			
			// aapt resource value: 0x7F07005F
			public const int backgroundFireflydarker = 2131165279;
			
			// aapt resource value: 0x7F07005E
			public const int back_arrow = 2131165278;
			
			// aapt resource value: 0x7F070060
			public const int btn_checkbox_checked_mtrl = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int btn_checkbox_checked_to_unchecked_mtrl_animation = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int btn_checkbox_unchecked_mtrl = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int btn_checkbox_unchecked_to_checked_mtrl_animation = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int btn_radio_off_mtrl = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int btn_radio_off_to_on_mtrl_animation = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int btn_radio_on_mtrl = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int btn_radio_on_to_off_mtrl_animation = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int cutearmsupghostsmol = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int cutearmsupghostsmolblue = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int cutearmsupghostsmolpurp = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int design_bottom_navigation_item_background = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int design_fab_background = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int design_ic_visibility = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int design_ic_visibility_off = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int design_password_eye = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int design_snackbar_background = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int forest = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int ghostpattern2 = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int ic_mtrl_chip_checked_black = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int ic_mtrl_chip_checked_circle = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int ic_mtrl_chip_close_circle = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int jackolanternremoved2 = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int knightpic = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int little_red_flag = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int mtrl_snackbar_background = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int mtrl_tabs_default_indicator = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int navigation_empty_icon = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int notification_action_background = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int notification_bg = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int notification_bg_low = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int notification_bg_low_normal = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int notification_bg_low_pressed = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int notification_bg_normal = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int notification_bg_normal_pressed = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int notification_icon_background = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int notification_template_icon_bg = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int notification_template_icon_low_bg = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int notification_tile_bg = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int notify_panel_notification_icon_bg = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int snowtreesmol = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int tooltip_frame_dark = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int tooltip_frame_light = 2131165322;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F080006
			public const int accessibility_action_clickable_span = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int accessibility_custom_action_0 = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int accessibility_custom_action_1 = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int accessibility_custom_action_10 = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int accessibility_custom_action_11 = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int accessibility_custom_action_12 = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int accessibility_custom_action_13 = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int accessibility_custom_action_14 = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int accessibility_custom_action_15 = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int accessibility_custom_action_16 = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int accessibility_custom_action_17 = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int accessibility_custom_action_18 = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int accessibility_custom_action_19 = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int accessibility_custom_action_2 = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int accessibility_custom_action_20 = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int accessibility_custom_action_21 = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int accessibility_custom_action_22 = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int accessibility_custom_action_23 = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int accessibility_custom_action_24 = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int accessibility_custom_action_25 = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int accessibility_custom_action_26 = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int accessibility_custom_action_27 = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int accessibility_custom_action_28 = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int accessibility_custom_action_29 = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int accessibility_custom_action_3 = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int accessibility_custom_action_30 = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int accessibility_custom_action_31 = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int accessibility_custom_action_4 = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int accessibility_custom_action_5 = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int accessibility_custom_action_6 = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int accessibility_custom_action_7 = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int accessibility_custom_action_8 = 2131230757;
			
			// aapt resource value: 0x7F080026
			public const int accessibility_custom_action_9 = 2131230758;
			
			// aapt resource value: 0x7F080038
			public const int actions = 2131230776;
			
			// aapt resource value: 0x7F080027
			public const int action_bar = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int action_bar_activity_content = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int action_bar_container = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int action_bar_root = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int action_bar_spinner = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int action_bar_subtitle = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int action_bar_title = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int action_container = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int action_context_bar = 2131230767;
			
			// aapt resource value: 0x7F080030
			public const int action_divider = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int action_image = 2131230769;
			
			// aapt resource value: 0x7F080032
			public const int action_menu_divider = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int action_menu_presenter = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int action_mode_bar = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int action_mode_bar_stub = 2131230773;
			
			// aapt resource value: 0x7F080036
			public const int action_mode_close_button = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int action_text = 2131230775;
			
			// aapt resource value: 0x7F080039
			public const int activity_chooser_view_content = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int add = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int alertTitle = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int all = 2131230780;
			
			// aapt resource value: 0x7F080000
			public const int ALT = 2131230720;
			
			// aapt resource value: 0x7F08003D
			public const int always = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int async = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int auto = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int beginning = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int blocking = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int bottom = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int browser_actions_header_text = 2131230787;
			
			// aapt resource value: 0x7F080046
			public const int browser_actions_menu_items = 2131230790;
			
			// aapt resource value: 0x7F080044
			public const int browser_actions_menu_item_icon = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int browser_actions_menu_item_text = 2131230789;
			
			// aapt resource value: 0x7F080047
			public const int browser_actions_menu_view = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int btnReturn = 2131230792;
			
			// aapt resource value: 0x7F080049
			public const int btnSave = 2131230793;
			
			// aapt resource value: 0x7F08004A
			public const int btnStart = 2131230794;
			
			// aapt resource value: 0x7F08004B
			public const int btnSubmit = 2131230795;
			
			// aapt resource value: 0x7F08004C
			public const int buttonPanel = 2131230796;
			
			// aapt resource value: 0x7F08004D
			public const int center = 2131230797;
			
			// aapt resource value: 0x7F08004E
			public const int center_horizontal = 2131230798;
			
			// aapt resource value: 0x7F08004F
			public const int center_vertical = 2131230799;
			
			// aapt resource value: 0x7F080050
			public const int checkbox = 2131230800;
			
			// aapt resource value: 0x7F080051
			public const int @checked = 2131230801;
			
			// aapt resource value: 0x7F080052
			public const int chronometer = 2131230802;
			
			// aapt resource value: 0x7F080053
			public const int clip_horizontal = 2131230803;
			
			// aapt resource value: 0x7F080054
			public const int clip_vertical = 2131230804;
			
			// aapt resource value: 0x7F080055
			public const int collapseActionView = 2131230805;
			
			// aapt resource value: 0x7F080056
			public const int container = 2131230806;
			
			// aapt resource value: 0x7F080057
			public const int content = 2131230807;
			
			// aapt resource value: 0x7F080058
			public const int contentPanel = 2131230808;
			
			// aapt resource value: 0x7F080059
			public const int coordinator = 2131230809;
			
			// aapt resource value: 0x7F080001
			public const int CTRL = 2131230721;
			
			// aapt resource value: 0x7F08005A
			public const int custom = 2131230810;
			
			// aapt resource value: 0x7F08005B
			public const int customPanel = 2131230811;
			
			// aapt resource value: 0x7F08005C
			public const int decor_content_parent = 2131230812;
			
			// aapt resource value: 0x7F08005D
			public const int default_activity_button = 2131230813;
			
			// aapt resource value: 0x7F08005E
			public const int design_bottom_sheet = 2131230814;
			
			// aapt resource value: 0x7F08005F
			public const int design_menu_item_action_area = 2131230815;
			
			// aapt resource value: 0x7F080060
			public const int design_menu_item_action_area_stub = 2131230816;
			
			// aapt resource value: 0x7F080061
			public const int design_menu_item_text = 2131230817;
			
			// aapt resource value: 0x7F080062
			public const int design_navigation_view = 2131230818;
			
			// aapt resource value: 0x7F080063
			public const int dialog_button = 2131230819;
			
			// aapt resource value: 0x7F080064
			public const int difficulty = 2131230820;
			
			// aapt resource value: 0x7F080065
			public const int disableHome = 2131230821;
			
			// aapt resource value: 0x7F080066
			public const int displayDifficulty = 2131230822;
			
			// aapt resource value: 0x7F080067
			public const int edit_query = 2131230823;
			
			// aapt resource value: 0x7F080068
			public const int end = 2131230824;
			
			// aapt resource value: 0x7F080069
			public const int enterAlways = 2131230825;
			
			// aapt resource value: 0x7F08006A
			public const int enterAlwaysCollapsed = 2131230826;
			
			// aapt resource value: 0x7F08006B
			public const int exitUntilCollapsed = 2131230827;
			
			// aapt resource value: 0x7F08006D
			public const int expanded_menu = 2131230829;
			
			// aapt resource value: 0x7F08006C
			public const int expand_activities_button = 2131230828;
			
			// aapt resource value: 0x7F08006E
			public const int fill = 2131230830;
			
			// aapt resource value: 0x7F080071
			public const int filled = 2131230833;
			
			// aapt resource value: 0x7F08006F
			public const int fill_horizontal = 2131230831;
			
			// aapt resource value: 0x7F080070
			public const int fill_vertical = 2131230832;
			
			// aapt resource value: 0x7F080072
			public const int @fixed = 2131230834;
			
			// aapt resource value: 0x7F080073
			public const int flBoard = 2131230835;
			
			// aapt resource value: 0x7F080074
			public const int forever = 2131230836;
			
			// aapt resource value: 0x7F080075
			public const int fragment_container_view_tag = 2131230837;
			
			// aapt resource value: 0x7F080002
			public const int FUNCTION = 2131230722;
			
			// aapt resource value: 0x7F080076
			public const int ghost_view = 2131230838;
			
			// aapt resource value: 0x7F080077
			public const int ghost_view_holder = 2131230839;
			
			// aapt resource value: 0x7F080078
			public const int group_divider = 2131230840;
			
			// aapt resource value: 0x7F080079
			public const int home = 2131230841;
			
			// aapt resource value: 0x7F08007A
			public const int homeAsUp = 2131230842;
			
			// aapt resource value: 0x7F08007B
			public const int icon = 2131230843;
			
			// aapt resource value: 0x7F08007C
			public const int icon_group = 2131230844;
			
			// aapt resource value: 0x7F08007D
			public const int ifRoom = 2131230845;
			
			// aapt resource value: 0x7F08007E
			public const int image = 2131230846;
			
			// aapt resource value: 0x7F08007F
			public const int info = 2131230847;
			
			// aapt resource value: 0x7F080080
			public const int italic = 2131230848;
			
			// aapt resource value: 0x7F080081
			public const int item_touch_helper_previous_elevation = 2131230849;
			
			// aapt resource value: 0x7F080082
			public const int labeled = 2131230850;
			
			// aapt resource value: 0x7F080083
			public const int largeLabel = 2131230851;
			
			// aapt resource value: 0x7F080084
			public const int left = 2131230852;
			
			// aapt resource value: 0x7F080085
			public const int line1 = 2131230853;
			
			// aapt resource value: 0x7F080086
			public const int line3 = 2131230854;
			
			// aapt resource value: 0x7F080087
			public const int listMode = 2131230855;
			
			// aapt resource value: 0x7F080088
			public const int list_item = 2131230856;
			
			// aapt resource value: 0x7F080089
			public const int masked = 2131230857;
			
			// aapt resource value: 0x7F08008A
			public const int message = 2131230858;
			
			// aapt resource value: 0x7F080003
			public const int META = 2131230723;
			
			// aapt resource value: 0x7F08008B
			public const int middle = 2131230859;
			
			// aapt resource value: 0x7F08008C
			public const int mini = 2131230860;
			
			// aapt resource value: 0x7F08008D
			public const int mtrl_child_content_container = 2131230861;
			
			// aapt resource value: 0x7F08008E
			public const int mtrl_internal_children_alpha_tag = 2131230862;
			
			// aapt resource value: 0x7F08008F
			public const int multiply = 2131230863;
			
			// aapt resource value: 0x7F080090
			public const int navigation_header_container = 2131230864;
			
			// aapt resource value: 0x7F080091
			public const int never = 2131230865;
			
			// aapt resource value: 0x7F080092
			public const int none = 2131230866;
			
			// aapt resource value: 0x7F080093
			public const int normal = 2131230867;
			
			// aapt resource value: 0x7F080094
			public const int notification_background = 2131230868;
			
			// aapt resource value: 0x7F080095
			public const int notification_main_column = 2131230869;
			
			// aapt resource value: 0x7F080096
			public const int notification_main_column_container = 2131230870;
			
			// aapt resource value: 0x7F080097
			public const int off = 2131230871;
			
			// aapt resource value: 0x7F080098
			public const int on = 2131230872;
			
			// aapt resource value: 0x7F080099
			public const int outline = 2131230873;
			
			// aapt resource value: 0x7F08009A
			public const int parallax = 2131230874;
			
			// aapt resource value: 0x7F08009B
			public const int parentPanel = 2131230875;
			
			// aapt resource value: 0x7F08009C
			public const int parent_matrix = 2131230876;
			
			// aapt resource value: 0x7F08009D
			public const int pin = 2131230877;
			
			// aapt resource value: 0x7F08009E
			public const int progress_circular = 2131230878;
			
			// aapt resource value: 0x7F08009F
			public const int progress_horizontal = 2131230879;
			
			// aapt resource value: 0x7F0800A0
			public const int radio = 2131230880;
			
			// aapt resource value: 0x7F0800A1
			public const int right = 2131230881;
			
			// aapt resource value: 0x7F0800A2
			public const int right_icon = 2131230882;
			
			// aapt resource value: 0x7F0800A3
			public const int right_side = 2131230883;
			
			// aapt resource value: 0x7F0800A4
			public const int save_non_transition_alpha = 2131230884;
			
			// aapt resource value: 0x7F0800A5
			public const int save_overlay_view = 2131230885;
			
			// aapt resource value: 0x7F0800A6
			public const int sbDifficulty = 2131230886;
			
			// aapt resource value: 0x7F0800A7
			public const int screen = 2131230887;
			
			// aapt resource value: 0x7F0800A8
			public const int scroll = 2131230888;
			
			// aapt resource value: 0x7F0800AC
			public const int scrollable = 2131230892;
			
			// aapt resource value: 0x7F0800A9
			public const int scrollIndicatorDown = 2131230889;
			
			// aapt resource value: 0x7F0800AA
			public const int scrollIndicatorUp = 2131230890;
			
			// aapt resource value: 0x7F0800AB
			public const int scrollView = 2131230891;
			
			// aapt resource value: 0x7F0800AD
			public const int search_badge = 2131230893;
			
			// aapt resource value: 0x7F0800AE
			public const int search_bar = 2131230894;
			
			// aapt resource value: 0x7F0800AF
			public const int search_button = 2131230895;
			
			// aapt resource value: 0x7F0800B0
			public const int search_close_btn = 2131230896;
			
			// aapt resource value: 0x7F0800B1
			public const int search_edit_frame = 2131230897;
			
			// aapt resource value: 0x7F0800B2
			public const int search_go_btn = 2131230898;
			
			// aapt resource value: 0x7F0800B3
			public const int search_mag_icon = 2131230899;
			
			// aapt resource value: 0x7F0800B4
			public const int search_plate = 2131230900;
			
			// aapt resource value: 0x7F0800B5
			public const int search_src_text = 2131230901;
			
			// aapt resource value: 0x7F0800B6
			public const int search_voice_btn = 2131230902;
			
			// aapt resource value: 0x7F0800B8
			public const int selected = 2131230904;
			
			// aapt resource value: 0x7F0800B7
			public const int select_dialog_listview = 2131230903;
			
			// aapt resource value: 0x7F080004
			public const int SHIFT = 2131230724;
			
			// aapt resource value: 0x7F0800B9
			public const int shortcut = 2131230905;
			
			// aapt resource value: 0x7F0800BA
			public const int showCustom = 2131230906;
			
			// aapt resource value: 0x7F0800BB
			public const int showHome = 2131230907;
			
			// aapt resource value: 0x7F0800BC
			public const int showTitle = 2131230908;
			
			// aapt resource value: 0x7F0800BD
			public const int smallLabel = 2131230909;
			
			// aapt resource value: 0x7F0800BE
			public const int snackbar_action = 2131230910;
			
			// aapt resource value: 0x7F0800BF
			public const int snackbar_text = 2131230911;
			
			// aapt resource value: 0x7F0800C0
			public const int snap = 2131230912;
			
			// aapt resource value: 0x7F0800C1
			public const int snapMargins = 2131230913;
			
			// aapt resource value: 0x7F0800C2
			public const int spacer = 2131230914;
			
			// aapt resource value: 0x7F0800C3
			public const int split_action_bar = 2131230915;
			
			// aapt resource value: 0x7F0800C4
			public const int src_atop = 2131230916;
			
			// aapt resource value: 0x7F0800C5
			public const int src_in = 2131230917;
			
			// aapt resource value: 0x7F0800C6
			public const int src_over = 2131230918;
			
			// aapt resource value: 0x7F0800C7
			public const int start = 2131230919;
			
			// aapt resource value: 0x7F0800C8
			public const int stretch = 2131230920;
			
			// aapt resource value: 0x7F0800C9
			public const int submenuarrow = 2131230921;
			
			// aapt resource value: 0x7F0800CA
			public const int submit_area = 2131230922;
			
			// aapt resource value: 0x7F080005
			public const int SYM = 2131230725;
			
			// aapt resource value: 0x7F0800CB
			public const int tabMode = 2131230923;
			
			// aapt resource value: 0x7F0800CC
			public const int tag_accessibility_actions = 2131230924;
			
			// aapt resource value: 0x7F0800CD
			public const int tag_accessibility_clickable_spans = 2131230925;
			
			// aapt resource value: 0x7F0800CE
			public const int tag_accessibility_heading = 2131230926;
			
			// aapt resource value: 0x7F0800CF
			public const int tag_accessibility_pane_title = 2131230927;
			
			// aapt resource value: 0x7F0800D0
			public const int tag_screen_reader_focusable = 2131230928;
			
			// aapt resource value: 0x7F0800D1
			public const int tag_transition_group = 2131230929;
			
			// aapt resource value: 0x7F0800D2
			public const int tag_unhandled_key_event_manager = 2131230930;
			
			// aapt resource value: 0x7F0800D3
			public const int tag_unhandled_key_listeners = 2131230931;
			
			// aapt resource value: 0x7F0800D4
			public const int text = 2131230932;
			
			// aapt resource value: 0x7F0800D5
			public const int text2 = 2131230933;
			
			// aapt resource value: 0x7F0800DA
			public const int textinput_counter = 2131230938;
			
			// aapt resource value: 0x7F0800DB
			public const int textinput_error = 2131230939;
			
			// aapt resource value: 0x7F0800DC
			public const int textinput_helper_text = 2131230940;
			
			// aapt resource value: 0x7F0800D6
			public const int textSpacerNoButtons = 2131230934;
			
			// aapt resource value: 0x7F0800D7
			public const int textSpacerNoTitle = 2131230935;
			
			// aapt resource value: 0x7F0800D8
			public const int textStart = 2131230936;
			
			// aapt resource value: 0x7F0800D9
			public const int text_input_password_toggle = 2131230937;
			
			// aapt resource value: 0x7F0800DD
			public const int time = 2131230941;
			
			// aapt resource value: 0x7F0800DE
			public const int title = 2131230942;
			
			// aapt resource value: 0x7F0800DF
			public const int titleDividerNoCustom = 2131230943;
			
			// aapt resource value: 0x7F0800E0
			public const int title_template = 2131230944;
			
			// aapt resource value: 0x7F0800E1
			public const int top = 2131230945;
			
			// aapt resource value: 0x7F0800E2
			public const int topPanel = 2131230946;
			
			// aapt resource value: 0x7F0800E3
			public const int touch_outside = 2131230947;
			
			// aapt resource value: 0x7F0800E4
			public const int transition_current_scene = 2131230948;
			
			// aapt resource value: 0x7F0800E5
			public const int transition_layout_save = 2131230949;
			
			// aapt resource value: 0x7F0800E6
			public const int transition_position = 2131230950;
			
			// aapt resource value: 0x7F0800E7
			public const int transition_scene_layoutid_cache = 2131230951;
			
			// aapt resource value: 0x7F0800E8
			public const int transition_transform = 2131230952;
			
			// aapt resource value: 0x7F0800E9
			public const int tvDisplayDifficulty = 2131230953;
			
			// aapt resource value: 0x7F0800EA
			public const int tvTime = 2131230954;
			
			// aapt resource value: 0x7F0800EB
			public const int tvTitle = 2131230955;
			
			// aapt resource value: 0x7F0800EC
			public const int tvWinMessage = 2131230956;
			
			// aapt resource value: 0x7F0800ED
			public const int @unchecked = 2131230957;
			
			// aapt resource value: 0x7F0800EE
			public const int uniform = 2131230958;
			
			// aapt resource value: 0x7F0800EF
			public const int unlabeled = 2131230959;
			
			// aapt resource value: 0x7F0800F0
			public const int up = 2131230960;
			
			// aapt resource value: 0x7F0800F1
			public const int useLogo = 2131230961;
			
			// aapt resource value: 0x7F0800F2
			public const int view_offset_helper = 2131230962;
			
			// aapt resource value: 0x7F0800F3
			public const int view_tree_saved_state_registry_owner = 2131230963;
			
			// aapt resource value: 0x7F0800F4
			public const int visible = 2131230964;
			
			// aapt resource value: 0x7F0800F5
			public const int visible_removing_fragment_view_tag = 2131230965;
			
			// aapt resource value: 0x7F0800F6
			public const int withText = 2131230966;
			
			// aapt resource value: 0x7F0800F7
			public const int wrap_content = 2131230967;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int abc_config_activityDefaultDur = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int abc_config_activityShortDur = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_bar_elevation_anim_duration = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int bottom_sheet_slide_duration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int cancel_button_image_alpha = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int config_tooltipAnimTime = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int design_snackbar_text_max_lines = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int design_tab_indicator_anim_duration_ms = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int hide_password_duration = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int mtrl_btn_anim_delay_ms = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int mtrl_btn_anim_duration_ms = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int mtrl_chip_anim_duration = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int mtrl_tab_indicator_anim_duration_ms = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int show_password_duration = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int status_bar_notification_info_maxnum = 2131296270;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7F0A0000
			public const int btn_checkbox_checked_mtrl_animation_interpolator_0 = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int btn_checkbox_checked_mtrl_animation_interpolator_1 = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_0 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_1 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int btn_radio_to_off_mtrl_animation_interpolator_0 = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int btn_radio_to_on_mtrl_animation_interpolator_0 = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int fast_out_slow_in = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int mtrl_fast_out_linear_in = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int mtrl_fast_out_slow_in = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int mtrl_linear = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int mtrl_linear_out_slow_in = 2131361802;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0B0000
			public const int abc_action_bar_title_item = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int abc_action_bar_up_container = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int abc_action_menu_item_layout = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int abc_action_menu_layout = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int abc_action_mode_bar = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int abc_action_mode_close_item_material = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int abc_activity_chooser_view = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int abc_activity_chooser_view_list_item = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int abc_alert_dialog_button_bar_material = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int abc_alert_dialog_material = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int abc_alert_dialog_title_material = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int abc_cascading_menu_item_layout = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int abc_dialog_title_material = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int abc_expanded_menu_layout = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int abc_list_menu_item_checkbox = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int abc_list_menu_item_icon = 2131427343;
			
			// aapt resource value: 0x7F0B0010
			public const int abc_list_menu_item_layout = 2131427344;
			
			// aapt resource value: 0x7F0B0011
			public const int abc_list_menu_item_radio = 2131427345;
			
			// aapt resource value: 0x7F0B0012
			public const int abc_popup_menu_header_item_layout = 2131427346;
			
			// aapt resource value: 0x7F0B0013
			public const int abc_popup_menu_item_layout = 2131427347;
			
			// aapt resource value: 0x7F0B0014
			public const int abc_screen_content_include = 2131427348;
			
			// aapt resource value: 0x7F0B0015
			public const int abc_screen_simple = 2131427349;
			
			// aapt resource value: 0x7F0B0016
			public const int abc_screen_simple_overlay_action_mode = 2131427350;
			
			// aapt resource value: 0x7F0B0017
			public const int abc_screen_toolbar = 2131427351;
			
			// aapt resource value: 0x7F0B0018
			public const int abc_search_dropdown_item_icons_2line = 2131427352;
			
			// aapt resource value: 0x7F0B0019
			public const int abc_search_view = 2131427353;
			
			// aapt resource value: 0x7F0B001A
			public const int abc_select_dialog_material = 2131427354;
			
			// aapt resource value: 0x7F0B001B
			public const int abc_tooltip = 2131427355;
			
			// aapt resource value: 0x7F0B001C
			public const int activity_main = 2131427356;
			
			// aapt resource value: 0x7F0B001D
			public const int board_view = 2131427357;
			
			// aapt resource value: 0x7F0B001E
			public const int browser_actions_context_menu_page = 2131427358;
			
			// aapt resource value: 0x7F0B001F
			public const int browser_actions_context_menu_row = 2131427359;
			
			// aapt resource value: 0x7F0B0020
			public const int custom_dialog = 2131427360;
			
			// aapt resource value: 0x7F0B0021
			public const int design_bottom_navigation_item = 2131427361;
			
			// aapt resource value: 0x7F0B0022
			public const int design_bottom_sheet_dialog = 2131427362;
			
			// aapt resource value: 0x7F0B0023
			public const int design_layout_snackbar = 2131427363;
			
			// aapt resource value: 0x7F0B0024
			public const int design_layout_snackbar_include = 2131427364;
			
			// aapt resource value: 0x7F0B0025
			public const int design_layout_tab_icon = 2131427365;
			
			// aapt resource value: 0x7F0B0026
			public const int design_layout_tab_text = 2131427366;
			
			// aapt resource value: 0x7F0B0027
			public const int design_menu_item_action_area = 2131427367;
			
			// aapt resource value: 0x7F0B0028
			public const int design_navigation_item = 2131427368;
			
			// aapt resource value: 0x7F0B0029
			public const int design_navigation_item_header = 2131427369;
			
			// aapt resource value: 0x7F0B002A
			public const int design_navigation_item_separator = 2131427370;
			
			// aapt resource value: 0x7F0B002B
			public const int design_navigation_item_subheader = 2131427371;
			
			// aapt resource value: 0x7F0B002C
			public const int design_navigation_menu = 2131427372;
			
			// aapt resource value: 0x7F0B002D
			public const int design_navigation_menu_item = 2131427373;
			
			// aapt resource value: 0x7F0B002E
			public const int design_text_input_password_icon = 2131427374;
			
			// aapt resource value: 0x7F0B002F
			public const int difficulty_dialog = 2131427375;
			
			// aapt resource value: 0x7F0B0030
			public const int mtrl_layout_snackbar = 2131427376;
			
			// aapt resource value: 0x7F0B0031
			public const int mtrl_layout_snackbar_include = 2131427377;
			
			// aapt resource value: 0x7F0B0032
			public const int notification_action = 2131427378;
			
			// aapt resource value: 0x7F0B0033
			public const int notification_action_tombstone = 2131427379;
			
			// aapt resource value: 0x7F0B0034
			public const int notification_template_custom_big = 2131427380;
			
			// aapt resource value: 0x7F0B0035
			public const int notification_template_icon_group = 2131427381;
			
			// aapt resource value: 0x7F0B0036
			public const int notification_template_part_chronometer = 2131427382;
			
			// aapt resource value: 0x7F0B0037
			public const int notification_template_part_time = 2131427383;
			
			// aapt resource value: 0x7F0B0038
			public const int select_dialog_item_material = 2131427384;
			
			// aapt resource value: 0x7F0B0039
			public const int select_dialog_multichoice_material = 2131427385;
			
			// aapt resource value: 0x7F0B003A
			public const int select_dialog_singlechoice_material = 2131427386;
			
			// aapt resource value: 0x7F0B003B
			public const int support_simple_spinner_dropdown_item = 2131427387;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int menuDif = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
